### ISSUE TITLE
Patch 9.2.7 / Season 4 Checklist

### ISSUE THREAD

**Issue by Voulk** [Voulk/QuestionablyEpic#726]
The following will need to take place before Season 4 goes live. PR's connected to the content can be submitted to the PTR branch. TODO: Add WoD effects to the list, but there are still a few questions around them.

Add new trinkets:
- [x] Faith's Crucible (Kara)
- [x] Fluctuating Energy (Kara)
- [x] Ingenious Mana Battery (Mechagon)

Add new effects:
- [x] Drape of Shame (Kara)
- [ ] Mechagon Ring sets (Mechagon)
- [ ] Neural Synapse Enhancer (Mechagon)
- [ ] Hyperthread Wristwraps (?) (Mechagon)
- [ ] Salvaged Mekacycle Shielding (Mechagon)

Upgrade Finder
- [x] Add Karazhan, Mechagon, Iron Docks & Grimrail
- [x] Add Castle Nathria & Sanctum of Domination back
- [x] Add a "Fated" item level option.
- [x] Remove the Shadowlands dungeons that won't be in season 4.

General
- [x] Update item levels across the app.
